version: "3"
    
services:
  clickhouse-ontime:
    image: yandex/clickhouse-server:latest
    volumes:
      - ./docker/clickhouse/load_ontime.sh:/docker-entrypoint-initdb.d/load_ontime.sh
      - /var/lib/clickhouse/
      - /var/log/clickhouse-server/
  clickhouse:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-latest}
    ports:
      - 8123:8123
      - 9000:9000
      - 5432:5432
      - 3306:3306
    volumes:
      - /var/log/clickhouse-server
      - ./docker/clickhouse/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./docker/clickhouse/postgres_dictionary.xml:/etc/clickhouse-server/postgres_dictionary.xml
      - ./docker/clickhouse/listen_ports.xml:/etc/clickhouse-server/config.d/listen_ports.xml

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=grafana
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    volumes:
      - ./:/var/lib/grafana/plugins/vertamedia-clickhouse/
      - ./docker/grafana/grafana-clickhouse-datasource.yaml:/etc/grafana/provisioning/datasources/grafana-clickhouse-datasource.yaml
      - ./docker/grafana/grafana-clickhouse-ontime-datasource.yaml:/etc/grafana/provisioning/datasources/grafana-clickhouse-ontime-datasource.yaml
      - ./docker/grafana/grafana-postgres-datasource.yaml:/etc/grafana/provisioning/datasources/grafana-postgres-datasource.yaml
      - ./docker/grafana/grafana-trickster-datasource.yaml:/etc/grafana/provisioning/datasources/grafana-trickster-datasource.yaml
      - ./docker/grafana/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml
      - ./docker/grafana/dashboards/:/var/lib/grafana/dashboards/

    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_LOG_LEVEL=debug
    ports:
      - 3000:3000
    depends_on:
      - clickhouse

  trickster:
    image: tricksterio/trickster:${TRICKSTER_VERSION:-latest}
    volumes:
      - ./docker/trickster/trickster.conf:/etc/trickster/trickster.conf
    ports:
      - 8480:8480
    depends_on:
      - clickhouse

  frontend_builder:
    image: node:lts
    working_dir: /grafana-clickhouse
    volumes:
    - ./:/grafana-clickhouse
    # for speedup npm install
    - "node_modules:/grafana-clickhouse/node_modules"
    command: |
      bash -xec '
        if [[ "3" == `ls -la ./node_modules/ | wc -l` ]]; then npm install --production=false; fi && \
        npm run build:prod && \
        npm run test:docker
      '

  backend_builder:
    image: golang:1.16
    working_dir: /go/src/grafana-clickhouse
    environment:
      GOCACHE: "/go-cache"
    volumes:
      - ./:/go/src/grafana-clickhouse
      - ./.cache:/go/pkg/mod
      - ./.cache:/go-cache
    command: |
      bash -xec "
        GOOS=linux GOARCH=amd64 go build -o ./dist/vertamedia-clickhouse-plugin_linux_amd64 ./pkg/ && \
        GOOS=linux GOARCH=arm64 go build -o ./dist/vertamedia-clickhouse-plugin_linux_arm64 ./pkg/ && \
        GOOS=windows GOARCH=amd64 go build -o ./dist/vertamedia-clickhouse-plugin_windows_amd64.exe ./pkg/ && \
        GOOS=darwin GOARCH=amd64 go build -o ./dist/vertamedia-clickhouse-plugin_darwin_amd64 ./pkg/ && \
        GOOS=darwin GOARCH=arm64 go build -o ./dist/vertamedia-clickhouse-plugin_darwin_arm64 ./pkg/ && \
        chmod +x ./dist/vertamedia-clickhouse-plugin*
      "

  plugin_signer:
    image: node:lts
    working_dir: /grafana-clickhouse
    volumes:
      - ./:/grafana-clickhouse
      # for speedup npm install
      - "node_modules:/grafana-clickhouse/node_modules"
    command: |
      bash -xec "
        if [[ ! -f ./node_modules/@grafana/toolkit/bin/grafana-toolkit.js ]]; then npm install --production=false; fi && \
        npm run sign
      "

volumes:
  node_modules:
