# see CONTRIBUTING.md
---
version: '3'
services:
  pmm-data:
    container_name: pmm-data
    image: percona/pmm-server:latest
    volumes:
      - "/srv"
      - "/var/lib/grafana"
  pmm-server:
    container_name: pmm-server
    image: percona/pmm-server:latest
    volumes:
      - "/srv"
      - "/var/lib/grafana"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - pmm-data
