version: '3'
services:
  cypress:
    image: cypress/included:3.4.0
    extra_hosts:
      - pmm-server:${CYPRESS_BASE_URL}
    environment:
      - CYPRESS_baseUrl=http://pmm-server:80
    working_dir: /e2e
    network_mode: bridge
    volumes:
      - ./:/e2e
